### ISSUE TITLE
0.2.6小米6官方miui10 开发8.12.27fc

### ISSUE THREAD

**Issue by KyuubiRan** [MlgmXyysd/EdXposed-Unofficial#1]
卡米 凉凉 0.2.5正常

**Comment by MlgmXyysd** [comment]
Please use template.([here](https://github.com/MlgmXyysd/EdXposed-Unofficial/issues/new?assignees=&labels=bug&template=bug_report.md&title=%E3%80%90BUG%E3%80%91%E5%9C%A8%E8%BF%99%E9%87%8C%E6%94%B9%E6%A0%87%E9%A2%98))
